from colorization_engine.factory.model_factory import build_model_pipeline
from colorization_engine.factory.loss_factory import build_loss
from colorization_engine.factory.registry import MODEL_REGISTRY, LOSS_REGISTRY