defaults:
  - model: mamba
  - loss: colorization
  - _self_

image_size: 256
device: null

training:
  lr: 1e-4
  weight_decay: 1e-4
  epochs: 8
  batch_size: 16
  num_workers: 4

  resume: null
  do_save: true
  amount_show: 4

data:
  # train: ["data/coco_train_2017/train100"]
  # train: ["data/coco_train_2017/train1k"]
  train: ["data/coco_train_2017/train2017"]
  # val: ["data/coco_val_2017/val100"]
  val: ["data/coco_val_2017/val2017"]
  test: [["data/NCD/NCD Dataset/Gray", "data/NCD/NCD Dataset/Color"], "data/coco_val_2017/val2017", "data/flowers"]